### ISSUE TITLE
Feature request: Compatibility with Detail Armor Bar mod

### ISSUE THREAD

**Issue by RashidFTW** [Crystal-Nest/leathered-boots#11]
**Is your feature request related to a problem? Please describe.**
Currently when using the Detail Armor Bar [mod](https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar), all Leathered armor pieces are shown as having Iron tier irrespective of their actual material (Diamond, Gold, etc.).

E.g: when wearing Leathered Netherite Boots (the last 1.5 armor bars are incorrectly displayed as iron):
![image](https://github.com/Crystal-Nest/leathered-boots/assets/160150516/bc04b6b4-db77-4420-8895-ca752b0f4e03)

**Describe the solution you'd like**
The author of the mod provides [documentation ](https://github.com/RedLime/DetailArmorBar/wiki/For-Developer-(API-Document))on the mod's GitHub page on how other mod developers can add compatibility via API.
I'm unsure; however, I hope that the process isn't too complicated and compatibility can be added.

**Describe alternatives you've considered**
I really love both mods! Although it's a minor nitpick, the alternative would be to give up the Detail Armor Bar mod which would be a letdown

**Additional context**

**Comment by Crystal-Spider** [comment]
Thanks for the report, this is a must have!

We are in the middle of some restructuring of our work methodology, so it might take some time.  
However, it will definitely happen!

**Comment by RashidFTW** [comment]
I am glad you share the same enthusiasm regarding this matter, excited for when it comes to fruition.

> We are in the middle of some restructuring of our work methodology, so it might take some time.

That's all right, all the best with that and thanks for the great work on the mods!

**Comment by Crystal-Spider** [comment]
Waiting for #12 and #13

**Comment by Crystal-Spider** [comment]
@RashidFTW which Minecraft version are you playing on?

**Comment by RashidFTW** [comment]
I am currently playing on Minecraft 1.20.1, however, I have been planning to update to 1.21 once all my mods are updated.

**Comment by Crystal-Spider** [comment]
Added with [v4.0.0](https://github.com/crystal-nest/leathered-boots/releases?q=4.0.0)

**Comment by RashidFTW** [comment]
Just did a quick-test, all seems to be working perfectly! Thanks for incorporating compatibility in your mod =D
