### ISSUE TITLE
Advanced Netherite Compatibility 1.21

### ISSUE THREAD

**Issue by makumaku1974** [Crystal-Nest/leathered-boots#14]
### I have confirmed no other issue asks for this

- [X] I have searched for existing issues

### Desired behavior

All types of leathered boots from said mod. 
![image](https://github.com/user-attachments/assets/f7be420d-a187-427c-ac6f-ce6c284e7f3c)

**Comment by Crystal-Spider** [comment]
Almost all mod compatibilities should be asked to the other mod, since Leathered Boots provides an API to easily register custom leathered boots.
