### ISSUE TITLE
Improve Readme and other documentation

### ISSUE THREAD

**Issue by Crystal-Spider** [Crystal-Nest/leathered-boots#3]
Update Readme with:
- ~~Proofreading~~
- ~~Modrinth~~
- ~~Links for versions to Modrinth~~

Update mod with:
- ~~New in-game picture (same as banner for Forge, square png for Fabric)~~
- ~~New GitHub social preview~~
- ~~Wiki~~
- ~~Readme update with API~~

Miscellaneous:
- ~~Update CurseForge and Modrinth description in accordance to the Readme~~
- ~~Update link on GitHub to go to Modrinth page~~

**Comment by FriedFridge** [comment]
Update Readme with:
- ~~Proofreading~~
- ~~Modrinth~~

Update mod with:
- New in-game picture (same as banner for Forge, square png for Fabric)
- New GitHub social preview

Miscellaneous:
- Update CurseForge and Modrinth description in accordance to the Readme
- Update link on GitHub to go to Modrinth page
- Whatever else comes to mind

**Comment by Crystal-Spider** [comment]
Waiting for #6

**Comment by Crystal-Spider** [comment]
Waiting for #8 and #9
